In [1]:
result1 = [i for i in range(10)]
print(result1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [2]:
result2 = [i for i in range(30)]
print(result2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [5]:
result3 = [i for i in range(30) if i%3 == 0]
print(result3)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]


In [7]:
result4 = [i for i in range(30) if i%3 == 0 or i%4 == 0]
print(result4)

[0, 3, 4, 6, 8, 9, 12, 15, 16, 18, 20, 21, 24, 27, 28]


In [8]:
result5 = [i for i in range(30) if i%6 == 0 else 100]
print(result5)

SyntaxError: invalid syntax (4256465714.py, line 1)

In [10]:
result6 = [i if i%6 == 0 else 100 for i in range(1,30,5)]
print(result6)

[100, 6, 100, 100, 100, 100]


In [11]:
import numpy as np


In [13]:
result6 = np.array(result6)
print(result6)

[100   6 100 100 100 100]


In [15]:
a = np.arange(20).reshape(4, -1)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [21]:
a = np.linspace(0, 20, 11)
print(a)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [42]:
import numpy as np
list1 = [10, 20, 30, 40]
list2 = [1, 2, 3, 4]

a1 = np.array(list1)
a2 = np.array(list2)

print(list1[1])

print(len(list1))

b=[]
for i in range (len(list1)):
    b.append(list1[i])
for i in range (len(list2)):
    b.append(list2[i])
    
print(b)


20
4
[10, 20, 30, 40, 1, 2, 3, 4]


In [46]:
b=np.array(b)
print(b)

[10 20 30 40  1  2  3  4]


In [47]:
print(b[b%3==0])

[30  3]
